### ISSUE TITLE
evaluation problems  (e.g., value(object))

### ISSUE THREAD

**Issue by zyh2022github** [FormalGeo/Datasets#1]
Hello！
I found that almost all Formal7k-v1 problems are evaluation problems  (e.g., value(object)), is it because the solver FGPS can only solve evaluation problems

**Comment by BitSecret** [comment]
This is because the data source for formalgeo7k consists entirely of numerical problems. FormalGeo unifies relational and numerical problem-solving goals. You can use "Relation" to represent relational problem-solving goals, such as "Relation(RightTriangle(ABC))".

**Comment by BitSecret** [comment]
We will be open-sourcing the dataset formalgeo7k-v2 soon. This dataset corrects some annotation errors from formalgeo7k-v1 and includes newly annotated images. Based on formalgeo7k-v2, the expanded dataset formalgeo30k balances relational and numerical problem-solving goals.
